'''
----interface_test                             项目文件夹目录
    ----common                                存放公共方法目录
            ----__init__.py                    初始化文件
            ----conf.py                          操作配置文件相关方法
            ----excelaction.py                Excel文件相关操作方法
            ----jsonaction.py                 Json文件相关操作方法
            ----logger.py                       记录日志的相关方法
            ----newfile.py                      获取最新文件的相关方法
            ----sendmail.py                   发送报告到指定邮箱的相关方法
            ----signture.py                    对数据进行签名的相关方法
            ----userinfo.py                    获取用户信息的相关方法
            ----config_test.conf             基本配置文件
    ----logs                                       存放日志的目录
    ----report                                    存放测试报告的目录
    ----test_data                                存放测试用例数据的目录
            ----login-1.json                    登录接口的测试用例数据
            ----logout-2.json                  退出登录接口的测试用例数据
    ----execute_test.py                       读取测试用例并执行测试用例
    ----test.bat                                    运行测试项目的批处理文件
'''
